SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/objects/Application__c.object
<CustomObject>
    <description>Collects information related to CMS applications that utilize cloud resources.</description>
    <fields>
        <fullName>Application_Acronym__c</fullName>
        <label>Application Acronym</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_ADO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary application development organization organization of the application.</description>
        <label>Primary ADO</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates an IT application with the project name/number on contract.</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Application_Point_of_Contact__c.object
<CustomObject>
    <description>Junction Object for Applications and Contacts</description>
    <fields>
        <fullName>Applications__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Application Point of Contacts</relationshipLabel>
        <relationshipName>Application_Point_of_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Point_Of_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Point Of Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Point of Contacts</relationshipLabel>
        <relationshipName>Application_Point_of_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Point of Contact</label>
    <nameField>
        <displayFormat>APOC -{00000}</displayFormat>
        <label>Application Point of Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Point of Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Application_Acronym__c</fullName>
        <label>Application Acronym</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_ADO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary ADO</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Acronym__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Acronym</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Number__c</fullName>
        <label>Project Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Ocean_Request__c.object
<CustomObject>
    <fields>
        <fullName>ADO_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADO Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ocean_request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AWSInstances__c</fullName>
        <label>AWS Resources</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VPC</fullName>
                </value>
                <value>
                    <fullName>EC2</fullName>
                </value>
                <value>
                    <fullName>EBS</fullName>
                </value>
                <value>
                    <fullName>ELB</fullName>
                </value>
                <value>
                    <fullName>RDS</fullName>
                </value>
                <value>
                    <fullName>RDS Backup Storage</fullName>
                </value>
                <value>
                    <fullName>EFS</fullName>
                </value>
                <value>
                    <fullName>S3</fullName>
                </value>
                <value>
                    <fullName>Data Transfer</fullName>
                </value>
                <value>
                    <fullName>Redshift</fullName>
                </value>
                <value>
                    <fullName>EMR</fullName>
                </value>
                <value>
                    <fullName>DynamoDB</fullName>
                </value>
                <value>
                    <fullName>Workspaces</fullName>
                </value>
                <value>
                    <fullName>Quicksight</fullName>
                </value>
                <value>
                    <fullName>Lambda</fullName>
                </value>
                <value>
                    <fullName>Other Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ApplicationName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Name</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipName>ocean_requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Acronym__c</fullName>
        <label>Application Acronym</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Name__c</fullName>
        <label>Application Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assumptions__c</fullName>
        <inlineHelpText>Document any assumptions related to your application and this cloud resource request you would like to share with the Cloud Resource Management Team.</inlineHelpText>
        <label>Assumptions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CSP_Option_Year__c</fullName>
        <label>CSP Option Year</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ocean_CSP_Option_Year</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cloud_Service_Provider_Project_Number__c</fullName>
        <label>Cloud Service Provider Project Number</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Approved_Resources__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Approved Resources</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MonthsInPoP__c</fullName>
        <label>Months In Period Of Performance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Additional_Funding_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Additional Funding Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_AWS_Accounts__c</fullName>
        <label>Number of AWS Accounts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OY_End_Date__c</fullName>
        <formula>ApplicationName__r.Option_Year_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OY End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OY_Start_Date__c</fullName>
        <formula>ApplicationName__r.Option_Year_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OY Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ocean_Wave__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ocean Wave</label>
        <referenceTo>Ocean_Wave__c</referenceTo>
        <relationshipLabel>ocean_requests</relationshipLabel>
        <relationshipName>ocean_requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option_Year_End_Date__c</fullName>
        <label>Option Year End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Option_Year_Start_Date__c</fullName>
        <label>Option Year Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PeriodOfPerformance__c</fullName>
        <label>Period Of Performance</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <label>Project_Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining_Months_in_OY__c</fullName>
        <formula>ApplicationName__r.Remaining_Months_in_OY__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Months in OY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>COR/GTL Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to CRMT</fullName>
                </value>
                <value>
                    <fullName>Initial Review Complete</fullName>
                </value>
                <value>
                    <fullName>ROM Requested</fullName>
                </value>
                <value>
                    <fullName>ROM Received</fullName>
                </value>
                <value>
                    <fullName>ROM Reviewed</fullName>
                </value>
                <value>
                    <fullName>RFP Requested</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>RFP Reviewed</fullName>
                </value>
                <value>
                    <fullName>RFP Accepted</fullName>
                </value>
                <value>
                    <fullName>ADO Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>CRMT Intake Review</fullName>
                </value>
                <value>
                    <fullName>Attestation Requested</fullName>
                </value>
                <value>
                    <fullName>CRMT Intake Review Completed</fullName>
                </value>
                <value>
                    <fullName>ROM Approved</fullName>
                </value>
                <value>
                    <fullName>RFP Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Estimated_Amount__c</fullName>
        <label>Total Estimated Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <inlineHelpText>The &quot;Wave&quot; is the submission period the Cloud Resources Management Team uses to manage Cloud Resource Requests from application teams.  Applications can only submit one cloud resource request per Wave.</inlineHelpText>
        <label>Wave</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ocean_Waves</valueSetName>
        </valueSet>
    </fields>
    <label>Ocean Request</label>
    <nameField>
        <label>Ocean_Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ocean_requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Number__c</fullName>
        <label>Project Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Acronym</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/globalValueSets/Ocean_CSP_Option_Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2019</fullName>
        <default>true</default>
        <label>2019</label>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <masterLabel>Ocean CSP Option Year</masterLabel>
</GlobalValueSet>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/globalValueSets/Ocean_Waves.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01/11/2019 - 12/31/2109</fullName>
        <default>true</default>
        <label>01/11/2019 - 12/31/2109</label>
    </customValue>
    <customValue>
        <fullName>01/01/2020 - 03/01/2020</fullName>
    </customValue>
    <masterLabel>Ocean Waves</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OceanUserAccessController.cls
public with sharing class OceanUserAccessController {
    public OceanUserAccessController() {}

    @AuraEnabled(cacheable = true)
    public static User getCurrentUser(){
        User u;
        u = [SELECT Id, name, email, contactId from User where Id=: UserInfo.getUserId()];
        return u;
    }

    @AuraEnabled(cacheable = false)
    public static List<Applications__c> getApplications(){
        User u = getCurrentUser();
        List<Application_Point_of_Contact__c> appList = [SELECT Id, Name, Applications__c,Applications__r.Id,COR_GTL__c,CRMS__c,ADO__c,CRMT__c,Point_Of_Contact__c,Read_Only__c
                              FROM Application_Point_of_Contact__c WHERE Point_Of_Contact__c =:u.contactId AND Read_Only__c = FALSE ORDER BY Name ASC];    
        List<Id> AppId = new List<Id>();
        for(Application_Point_of_Contact__c appPOC : appList){
            AppId.add(appPOC.Applications__c);
        }
        return [SELECT Id, Name, Primary_ADO__r.Name, Wave__c, Primary_ADO__c, Project_Acronym__r.Name, Project_Acronym__r.Project_Number__c, Application_Acronym__c, CSP_Option_Year__c FROM Applications__c WHERE ID IN :AppId];                    
    }

    @AuraEnabled(cacheable = true)
    public static Ocean_Wave__c getCurrentWave(){
        return [SELECT Id, Name, Active_Wave__c, CSP_Option_Year__c, CSP_Option_Year__r.Name, CSP_Option_Year__r.Remaining_Months_in_OY__c, Option_Year_End_Date__c,
                                     Option_Year_Start_Date__c, Wave_Start_Date__c, Wave_End_Date__c
                                     FROM Ocean_Wave__c WHERE Active_Wave__c = TRUE LIMIT 1];    
    }

    @AuraEnabled(cacheable = false)
    public static string getRole(String appId){
        User u = getCurrentUser();
        Application_Point_of_Contact__c app = [SELECT Id, Name, Applications__c,COR_GTL__c,CRMS__c,ADO__c,CRMT__c,Point_Of_Contact__c,Read_Only__c
                              FROM Application_Point_of_Contact__c WHERE Point_Of_Contact__c =:u.contactId AND Applications__c =: AppId LIMIT 1 ];    
        String Role;
        if(app.ADO__c == true)
            Role = 'ADO';
        else if(app.COR_GTL__c == true) 
            Role = 'COR/GTL';
        else if(app.CRMS__c == true)
            Role = 'CRMS';
        else if(app.CRMT__c == true)
            Role = 'CRMT';
        else if(app.Read_Only__c == true)
            Role = 'ReadOnly';

        return Role;       
    }

    @AuraEnabled(cacheable = false)
    public static List<OCEAN_Request__c> getDraftRequests(){
        User u = getCurrentUser();
        List<Application_Point_of_Contact__c> appList = [SELECT Id, Name, Applications__c,Applications__r.Id,COR_GTL__c,CRMS__c,ADO__c,CRMT__c,Point_Of_Contact__c,Read_Only__c
                              FROM Application_Point_of_Contact__c WHERE Point_Of_Contact__c =:u.contactId AND Read_Only__c = FALSE];    
        List<Id> AppId = new List<Id>();
        for(Application_Point_of_Contact__c appPOC : appList){
            AppId.add(appPOC.Applications__c);
        }
        return [SELECT Id,Name,ADO_Name__c,CreatedDate,  LastModifiedDate, AWSInstances__c, Application_Name__c, App_Team_Request_Status__c,ApplicationName__c,Assumptions__c, Cloud_Service_Provider_Project_Number__c,  Current_Approved_Resources__c, MonthsInPoP__c, No_Additional_Funding_Requested__c, Number_of_AWS_Accounts__c,OY_End_Date__c, OY_Start_Date__c, PeriodOfPerformance__c, ProjectName__c, Request_Status__c, Submitted_Date__c, Total_Estimated_Amount__c, Wave__c,Total_Estimated_Cost__c FROM OCEAN_Request__c WHERE Request_Status__c = 'Draft' AND ApplicationName__c IN :AppId ORDER BY Submitted_Date__c];       
    }

    @AuraEnabled(cacheable = false)
    public static List<OCEAN_Request__c> getSubmittedRequests(){
        User u = getCurrentUser();
        List<Application_Point_of_Contact__c> appList = [SELECT Id, Name, Applications__c,Applications__r.Id,COR_GTL__c,CRMS__c,ADO__c,CRMT__c,Point_Of_Contact__c,Read_Only__c
                              FROM Application_Point_of_Contact__c WHERE Point_Of_Contact__c =:u.contactId AND Read_Only__c = FALSE];    
        List<Id> AppId = new List<Id>();
        for(Application_Point_of_Contact__c appPOC : appList){
            AppId.add(appPOC.Applications__c);
        }
        return [SELECT Id,Name,ADO_Name__c,CreatedDate,  LastModifiedDate, AWSInstances__c, Application_Name__c, ApplicationName__c,Assumptions__c, Cloud_Service_Provider_Project_Number__c,  Current_Approved_Resources__c, MonthsInPoP__c, No_Additional_Funding_Requested__c, Number_of_AWS_Accounts__c,OY_End_Date__c, OY_Start_Date__c, PeriodOfPerformance__c, ProjectName__c, Request_Status__c, Submitted_Date__c, Total_Estimated_Amount__c, Wave__c,App_Team_Request_Status__c,Total_Estimated_Cost__c FROM OCEAN_Request__c WHERE Request_Status__c NOT IN ('Approved', 'Draft') AND ApplicationName__c IN :APPId ORDER BY Submitted_Date__c];       
    }

    @AuraEnabled(cacheable = false)
    public static List<OCEAN_Request__c> getApprovedRequests(){
        User u = getCurrentUser();
        List<Application_Point_of_Contact__c> appList = [SELECT Id, Name, Applications__c,Applications__r.Id,COR_GTL__c,CRMS__c,ADO__c,CRMT__c,Point_Of_Contact__c,Read_Only__c
                              FROM Application_Point_of_Contact__c WHERE Point_Of_Contact__c =:u.contactId AND Read_Only__c = FALSE];    
        List<Id> AppId = new List<Id>();
        for(Application_Point_of_Contact__c appPOC : appList){
            AppId.add(appPOC.Applications__c);
        }
        return [SELECT Id,Name,ADO_Name__c,CreatedDate,  LastModifiedDate, App_Team_Request_Status__c,AWSInstances__c, Application_Name__c, ApplicationName__c,Assumptions__c, Cloud_Service_Provider_Project_Number__c,  Current_Approved_Resources__c, MonthsInPoP__c, No_Additional_Funding_Requested__c, Number_of_AWS_Accounts__c,OY_End_Date__c, OY_Start_Date__c, PeriodOfPerformance__c, ProjectName__c, Request_Status__c, Submitted_Date__c, Total_Estimated_Amount__c, Wave__c,Total_Estimated_Cost__c FROM OCEAN_Request__c WHERE Request_Status__c = 'Approved' AND ApplicationName__c IN :APPId ORDER BY Submitted_Date__c];       
    }

    @AuraEnabled(cacheable = true)
    public static List<Application_Point_of_Contact__c> getAppPOCs(){  
        User u = getCurrentUser();            
        return [SELECT Id,Name,Applications__c,Applications__r.Id,COR_GTL__c,CRMS__c,ADO__c,CRMT__c,Point_Of_Contact__c,Read_Only__c 
                      FROM Application_Point_of_Contact__c WHERE Point_Of_Contact__c =: u.contactId];
    }

    @AuraEnabled(cacheable = true)
    public static List<UserRole__c> getADORoleAttributes(){
        return [SELECT Id,Name,Approve_Request_Submission__c,Create__c,Review__c,Approve__c FROM UserRole__c WHERE name = 'ADO' ];
    }

    @AuraEnabled(cacheable = true)
    public static List<UserRole__c> getCORGTLRoleAttributes(){
        return [SELECT Id,Name,Approve_Request_Submission__c,Create__c,Review__c,Approve__c FROM UserRole__c WHERE name = 'COR/GTL' ];
    }

    @AuraEnabled(cacheable = true)
    public static List<UserRole__c> getCRMSRoleAttributes(){
        return [SELECT Id,Name,Approve_Request_Submission__c,Create__c,Review__c,Approve__c FROM UserRole__c WHERE name = 'CRMS' ];
    }

    @AuraEnabled(cacheable = true)
    public static List<UserRole__c> getCRMTRoleAttributes(){
        return [SELECT Id,Name,Approve_Request_Submission__c,Create__c,Review__c,Approve__c FROM UserRole__c WHERE name = 'CRMT' ];
    }

}