SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/objects/Application__c.object
<CustomObject>
    <description>Collects information related to CMS applications that utilize cloud resources.</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Ocean_Ebs_Storage__c.object
<CustomObject>
    <fields>
        <fullName>ADO_Notes__c</fullName>
        <label>ADO Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AWS_Region__c</fullName>
        <label>AWS Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ocean_AWS_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Component__c</fullName>
        <label>Application Component</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSP_Option_Year__c</fullName>
        <label>CSP Option Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EBS_Storage_Id__c</fullName>
        <displayFormat>EBS-STORAGE-{0000}</displayFormat>
        <label>EBS Storage Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ocean_Environment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Cost__c</fullName>
        <label>Estimated Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Monthly_Cost__c</fullName>
        <label>Estimated Monthly Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IOPS__c</fullName>
        <label>IOPS</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Months_Requested__c</fullName>
        <label>Number of Months Requested</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Volumes__c</fullName>
        <label>Number of Volumes</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ocean_Request_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>OCEAN_REQUEST</label>
        <referenceTo>Ocean_Request__c</referenceTo>
        <relationshipName>Ocean_Ebs_Request</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resource_Status__c</fullName>
        <label>Resource Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ocean_Resource_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Snapshot_Storage_GB_Per_Month__c</fullName>
        <label>Snapshot Storage (GB/Month)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Storage_Size_GB__c</fullName>
        <label>Storage Size (GB)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volume_Type__c</fullName>
        <label>Volume Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ocean_EBS_VolumeType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wave_Submitted__c</fullName>
        <label>Wave Submitted</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ocean EBS Storage</label>
    <nameField>
        <label>Ocean_Ebs_Storage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ocean_Ebs_Storages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/objects/Ocean_Ebs_Storage__c.object
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/globalValueSets/Ocean_AWS_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>US-East/US-Standard (Virginia)</fullName>
    </customValue>
    <masterLabel>AWS Region</masterLabel>
</GlobalValueSet>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/globalValueSets/Ocean_EBS_VolumeType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>General Purpose, SSD-backed</fullName>
    </customValue>
    <customValue>
        <fullName>Provisioned IOPS, SSD-backed</fullName>
    </customValue>
    <customValue>
        <fullName>Throughput Optimized HDD, HDD-backed</fullName>
    </customValue>
    <customValue>
        <fullName>Cold HDD, HDD-backed</fullName>
    </customValue>
    <customValue>
        <fullName>Magnetic, HDD-backed</fullName>
    </customValue>
    <customValue>
        <fullName>EBS General Purpose SSD (gp2)</fullName>
        <isActive>false</isActive>
        <label>EBS General Purpose SSD (gp2)</label>
    </customValue>
    <customValue>
        <fullName>EBS Provisioned IOPS SSD (io1)</fullName>
        <isActive>false</isActive>
        <label>EBS Provisioned IOPS SSD (io1)</label>
    </customValue>
    <customValue>
        <fullName>EBS Throughput Optimized HDD (st1)</fullName>
        <isActive>false</isActive>
        <label>EBS Throughput Optimized HDD (st1)</label>
    </customValue>
    <customValue>
        <fullName>EBS Cold HDD (sc1)</fullName>
        <isActive>false</isActive>
        <label>EBS Cold HDD (sc1)</label>
    </customValue>
    <customValue>
        <fullName>Magnetic</fullName>
        <isActive>false</isActive>
        <label>Magnetic</label>
    </customValue>
    <masterLabel>EBS VolumeType</masterLabel>
</GlobalValueSet>

SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/globalValueSets/Ocean_Environment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Development</fullName>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
    </customValue>
    <customValue>
        <fullName>Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Production</fullName>
    </customValue>
    <customValue>
        <fullName>Management</fullName>
    </customValue>
    <masterLabel>Environment</masterLabel>
</GlobalValueSet>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/globalValueSets/Ocean_Resource_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Discontinuation</fullName>
    </customValue>
    <customValue>
        <fullName>Continuation</fullName>
    </customValue>
    <masterLabel>Resource Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OceanEbsStorageController.cls
public with sharing class OceanEbsStorageController {
    @AuraEnabled(Cacheable = false)
    public static List<Ocean_Ebs_Storage__c> getEbsStorages(String oceanRequestId){
        return[SELECT ADO_Notes__c,Application__c,Application_Component__c,AWS_Region__c,CSP_Option_Year__c,EBS_Storage_Id__c,Environment__c,Estimated_Cost__c,Estimated_Monthly_Cost__c,IOPS__c,Number_of_Months_Requested__c,Number_of_Volumes__c,Project_Name__c,Resource_Status__c,Snapshot_Storage_GB_Per_Month__c,Storage_Size_GB__c,Volume_Type__c,Wave_Submitted__c FROM Ocean_Ebs_Storage__c WHERE Ocean_Request_Id__c =:oceanRequestId ORDER BY  CreatedDate];
    }
}