SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/objects/Application__c.object
<CustomObject>
    <description>Collects information related to CMS applications that utilize cloud resources.</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Ocean_Vpc_Request__c.object
<CustomObject>
    <fields>
        <fullName>ADO_Notes__c</fullName>
        <label>ADO Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AWS_Region__c</fullName>
        <label>AWS Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ocean_Aws_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Component__c</fullName>
        <label>Application Component</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ocean_Environment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_VPCs__c</fullName>
        <label>Number of VPCs</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ocean_Request_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>OCEAN_REQUEST</label>
        <referenceTo>Ocean_Request__c</referenceTo>
        <relationshipName>Ocean_vpc</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resource_Status__c</fullName>
        <label>Resource Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ocean_Resource_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tenancy__c</fullName>
        <label>Tenancy</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ocean_Tenancy</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>VPC_Request_Id__c</fullName>
        <displayFormat>OCEAN-VPC-{00000}</displayFormat>
        <label>VPC Request Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Wave_Submitted__c</fullName>
        <label>Wave Submitted</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Ocean_Vpc_Request</label>
    <nameField>
        <label>VPC ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ocean_Vpc_Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/globalValueSets/Ocean_AWS_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>US-East/US-Standard (Virginia)</fullName>
    </customValue>
    <masterLabel>AWS Region</masterLabel>
</GlobalValueSet>

SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/globalValueSets/Ocean_Environment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Development</fullName>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
    </customValue>
    <customValue>
        <fullName>Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Production</fullName>
    </customValue>
    <customValue>
        <fullName>Management</fullName>
    </customValue>
    <masterLabel>Environment</masterLabel>
</GlobalValueSet>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/globalValueSets/Ocean_Resource_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Discontinuation</fullName>
    </customValue>
    <customValue>
        <fullName>Continuation</fullName>
    </customValue>
    <masterLabel>Resource Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OceanVpcRequestController.cls
public with sharing class OceanVpcRequestController {
    @AuraEnabled(Cacheable = false)
    public static List<Ocean_Vpc_Request__c> getVpcRequests(String oceanRequestId){
        return [SELECT VPC_Request_Id__c, ADO_Notes__c,Application__c,Application_Component__c,AWS_Region__c,Tenancy__c,Project_Name__c,Resource_Status__c,Environment__c,Wave_Submitted__c, Number_of_VPCs__c FROM Ocean_Vpc_Request__c WHERE Ocean_Request_Id__c =:oceanRequestId ORDER BY  CreatedDate];
    }
}