force-app/main/default/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>SAVI_File_Scan_Status__c</fullName>
        <label>SAVI File Scan Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/ContentVersion.object
    <fields>
        <fullName>Ocean_File_Type__c</fullName>
        <label>Ocean File Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/ContentVersion.object
    <fields>
        <fullName>Ocean_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ocean_Request</label>
        <referenceTo>Ocean_Request__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/ContentVersion.object
    <fields>
        <fullName>Ocean_Request_Id__c</fullName>
        <label>Ocean Request Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Ocean_Request__c.object
<CustomObject>
    <fields>
        <fullName>OCEAN_REQUEST_ID__c</fullName>
        <displayFormat>OCEAN-{00000}</displayFormat>
        <label>OCEAN_REQUEST_ID</label>
        <type>AutoNumber</type>
    </fields>
    <label>Ocean Request</label>
    <nameField>
        <label>Ocean_Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ocean_requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OceanFileController.cls
public inherited sharing class OceanFileController {
   @AuraEnabled
    public static ContentVersion saveFile(Id idParent, String fileType, String strFileName, String base64Data) {
        // Decoding base64Data
        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
        
        // inserting file
        ContentVersion cv = new ContentVersion();
        cv.Title = strFileName;
        cv.PathOnClient = '/' + strFileName;
        cv.FirstPublishLocationId = idParent;
        cv.Ocean_Request_Id__c = idParent;
        cv.Ocean_Request__c = idParent;
        cv.Ocean_File_Type__c = fileType;
        cv.VersionData = EncodingUtil.base64Decode(base64Data);
        cv.IsMajorVersion = true;
        if (!Schema.sObjectType.ContentVersion.fields.title.isCreateable() || 
            !Schema.sObjectType.ContentVersion.fields.PathOnClient.isCreateable() || 
            !Schema.sObjectType.ContentVersion.fields.FirstPublishLocationId.isCreateable() || 
            !Schema.sObjectType.ContentVersion.fields.Ocean_Request_Id__c.isCreateable() ||
            !Schema.sObjectType.ContentVersion.fields.Ocean_Request__c.isCreateable() ||
            !Schema.sObjectType.ContentVersion.fields.Ocean_File_Type__c.isCreateable() ||
            !Schema.sObjectType.ContentVersion.fields.VersionData.isCreateable() ||
            !Schema.sObjectType.ContentVersion.fields.IsMajorVersion.isCreateable()){
            return null;
        }
        insert cv;
        return cv;
    }

    @AuraEnabled
    public static List<FileUploadWrapper> relatedFiles(Id idParent){
        List<id> lstConDocs = new List<id>();
        List<contentversion> cvList = new List<contentversion>();
        List<FileUploadWrapper> fileWrapperList = new List<FileUploadWrapper>();

        for(ContentDocumentLink cntLink : [Select Id, ContentDocumentId From ContentDocumentLink Where LinkedEntityId =:idParent]) {
            lstConDocs.add(cntLink.ContentDocumentId);
        }
 
        if(!lstConDocs.isEmpty()) {
            cvList = [SELECT Id, Title, ContentDocumentId, SAVI_File_Scan_Status__c FROM ContentVersion WHERE ContentDocumentId IN :lstConDocs];
        }
        
        for (ContentVersion cv : cvList) {
            FileUploadWrapper fileWrapper = new FileUploadWrapper();
            fileWrapper.id = cv.Id;
            fileWrapper.url = '/sfc/servlet.shepherd/document/download/'+cv.ContentDocumentId;
            fileWrapper.title = cv.Title;
            fileWrapper.contentDocumentId = cv.ContentDocumentId;
            fileWrapper.scanStatus = cv.SAVI_File_Scan_Status__c;
            fileWrapperList.add(fileWrapper);
        }

        return fileWrapperList;   
    }
    
}