SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Application_Point_of_Contact__c.object
<CustomObject>
    <description>Junction Object for Applications and Contacts</description>
    <fields>
        <fullName>Applications__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applications</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipLabel>Application Point of Contacts</relationshipLabel>
        <relationshipName>Application_Point_of_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Point_Of_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Point Of Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Point of Contacts</relationshipLabel>
        <relationshipName>Application_Point_of_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <label>Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ADO</fullName>
                </value>
                <value>
                    <fullName>COR/GTL</fullName>
                </value>
                <value>
                    <fullName>CRMS</fullName>
                </value>
                <value>
                    <fullName>CRMT</fullName>
                </value>
                <value>
                    <fullName>Read Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Point of Contact</label>
    <nameField>
        <displayFormat>APOC -{00000}</displayFormat>
        <label>Application Point of Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Point of Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Applications__c.object
<CustomObject>
    <label>Applications</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Ocean_Wave__c.object
<CustomObject>
    <label>Ocean Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ocean Waves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/UserRoleAccess__c.object
<CustomObject>
    <fields>
        <fullName>Approve_Request_Submission__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approve Request Submission</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approve__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approve</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hierarchy__c</fullName>
        <label>Hierarchy</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Review</label>
        <type>Checkbox</type>
    </fields>
    <label>UserRoleAccess</label>
    <nameField>
        <label>Roles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserRoleAccesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test Classes/Test_OceanUserAccessController.cls
@isTest
public with sharing class Test_OceanUserAccessController {
    public static testMethod void oceanUserAccessControllerTest() {
        test.startTest();

        Ocean_Wave__c currentWave = new Ocean_Wave__c();
        currentWave.Active_Wave__c = true;
        currentWave.Wave_Start_Date__c = System.today();
        currentWave.Wave_End_Date__c = System.today() + 90;
        insert currentWave;

        Applications__c app = TestDataFactory.getApplication();
        User u = OceanUserAccessController.getCurrentUser();
        Application_Point_of_Contact__c appPOC = new Application_Point_of_Contact__c();
        appPOC.Applications__c = app.id;
        appPOC.Point_Of_Contact__c = u.ContactId;
        appPOC.Roles__c = 'ADO';
        insert appPOC;
        
        UserRoleAccess__c roleAccess = new UserRoleAccess__c();
        roleAccess.Name = 'ADO';
        roleAccess.Approve__c = false;
        roleAccess.FileUpload__c = true;
        roleAccess.CRMTFileUpload__c = false;
        roleAccess.Approve_Request_Submission__c = false;
        roleAccess.Create__c = true;
        roleAccess.Hierarchy__c = '1'; 
        roleAccess.Review__c = false;
        insert roleAccess;

        OceanUserAccessController.getCurrentUser();
        OceanUserAccessController.getApplications();
        OceanUserAccessController.getCurrentWave();
        OceanUserAccessController.getUserRoleAccess(app.id);
        OceanUserAccessController.getDraftRequests();
        OceanUserAccessController.getSubmittedRequests();
        OceanUserAccessController.getApprovedRequests();
        test.stopTest();
    }
}