SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Project_Number__c</fullName>
        <label>Project Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/OCEAN_Ec2Instance__c.object
<CustomObject>
    <label>OCEAN EC2 Instance</label>
    <nameField>
        <displayFormat>EC2-{0000}</displayFormat>
        <label>EC2 Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCEAN_Ec2Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Ocean_Request__c.object
<CustomObject>
    <fields>
        <fullName>AWSInstances__c</fullName>
        <label>AWS Resources</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VPC</fullName>
                </value>
                <value>
                    <fullName>EC2</fullName>
                </value>
                <value>
                    <fullName>EBS</fullName>
                </value>
                <value>
                    <fullName>ELB</fullName>
                </value>
                <value>
                    <fullName>RDS</fullName>
                </value>
                <value>
                    <fullName>RDS Backup Storage</fullName>
                </value>
                <value>
                    <fullName>EFS</fullName>
                </value>
                <value>
                    <fullName>S3</fullName>
                </value>
                <value>
                    <fullName>Data Transfer</fullName>
                </value>
                <value>
                    <fullName>Redshift</fullName>
                </value>
                <value>
                    <fullName>EMR</fullName>
                </value>
                <value>
                    <fullName>DynamoDB</fullName>
                </value>
                <value>
                    <fullName>Workspaces</fullName>
                </value>
                <value>
                    <fullName>Quicksight</fullName>
                </value>
                <value>
                    <fullName>Lambda</fullName>
                </value>
                <value>
                    <fullName>Other Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cloud_Service_Provider_Project_Number__c</fullName>
        <label>Cloud Service Provider Project Number</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ocean_Wave__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ocean Wave</label>
        <referenceTo>Ocean_Wave__c</referenceTo>
        <relationshipLabel>ocean_requests</relationshipLabel>
        <relationshipName>ocean_requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option_Year_End_Date__c</fullName>
        <label>Option Year End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Option_Year_Start_Date__c</fullName>
        <label>Option Year Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Option_Year__c</fullName>
        <label>Option Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <label>Project_Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>COR/GTL Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to CRMT</fullName>
                </value>
                <value>
                    <fullName>Initial Review Complete</fullName>
                </value>
                <value>
                    <fullName>ROM Requested</fullName>
                </value>
                <value>
                    <fullName>ROM Received</fullName>
                </value>
                <value>
                    <fullName>ROM Reviewed</fullName>
                </value>
                <value>
                    <fullName>RFP Requested</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>RFP Reviewed</fullName>
                </value>
                <value>
                    <fullName>RFP Accepted</fullName>
                </value>
                <value>
                    <fullName>ADO Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>CRMT Intake Review</fullName>
                </value>
                <value>
                    <fullName>Attestation Requested</fullName>
                </value>
                <value>
                    <fullName>CRMT Intake Review Completed</fullName>
                </value>
                <value>
                    <fullName>ROM Approved</fullName>
                </value>
                <value>
                    <fullName>RFP Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ocean Request</label>
    <nameField>
        <label>Ocean_Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ocean_requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Ocean_Wave__c.object
<CustomObject>
    <label>Ocean Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ocean Waves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Option_Year__c.object
<CustomObject>
    <fields>
        <fullName>Option_Year_End_Date__c</fullName>
        <label>Option Year End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Option_Year_Start_Date__c</fullName>
        <label>Option Year Start Date</label>
        <type>Date</type>
    </fields>
    <label>Option Year</label>
    <nameField>
        <label>CSP Option Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Option Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Number__c</fullName>
        <label>Project Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Acronym</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_OceanController.cls
@isTest
public with sharing class Test_OceanController {
    public static testMethod void oceanControllerTest(){
        test.startTest();
        OCEAN_Request__c oceanRequest = new OCEAN_Request__c();
        oceanRequest.Cloud_Service_Provider_Project_Number__c = '48';
        oceanRequest.AWSInstances__c = 'EC2';
        oceanRequest.ProjectName__c = 'Ocean';
        oceanRequest.name = 'CRR-211';
        oceanRequest.Request_Status__c = 'Draft';
        oceanRequest.CRMT_Request_Status__c = 'Draft';
        oceanRequest.Review_Status__c = 'Draft';
        oceanRequest.Approval_Comments__c = 'Comments';
        oceanRequest.Review_Outcome__c = 'Approved';
        insert oceanRequest;

        Project__c proj = new Project__c();
        proj.Project_Number__c = '48';
        proj.name = 'OCEAN';
        insert proj;

        Applications__c app = new Applications__c();
        insert app;

        Option_Year__c oy = new Option_Year__c();
        oy.Option_Year_Start_Date__c = System.today();
        oy.Option_Year_End_Date__c = System.today() + 120;
        insert oy;

        Ocean_Wave__c wave = new Ocean_Wave__c();
        wave.name = 'Wave 2020';
        wave.Active_Wave__c = true;
        wave.ADO_Submission_Due_Date__c = Date.newInstance(2020, 12, 9);
        wave.Wave_Start_Date__c = system.today();
        wave.Wave_End_Date__c = System.today() + 90 ;
        insert wave;

        OceanRequestWrapper request = new OceanRequestWrapper();
        request.id = oceanRequest.Id;
        request.displayId = oceanRequest.Name;
        request.awsInstances = oceanRequest.AWSInstances__c.split(';');        
        request.requestStatus = oceanRequest.Request_Status__c;
        request.CRMTStatus = oceanRequest.CRMT_Request_Status__c;
        request.reviewStage = oceanRequest.Review_Status__c;
        request.comment = oceanRequest.Approval_Comments__c;
        request.reviewOutcome = oceanRequest.Review_Outcome__c;
        request.applicationDetails = getApplicationDetails(app.id);

        OceanWaveWrapper waveWrapper = new OceanWaveWrapper();
        waveWrapper.isActive = true;
        waveWrapper.waveStartDate = system.today();
        waveWrapper.waveEndDate = wave.Wave_Start_Date__c;
        waveWrapper.cspOY = '2020';
        waveWrapper.oyEndDate = oy.Option_Year_End_Date__c;
        waveWrapper.oyStartDate = oy.Option_Year_Start_Date__c;
        waveWrapper.oyMonthsRemaining = 11;
        
		List<OceanAWSAccountWrapper> awsWrapperList = new List<OceanAWSAccountWrapper>();
        OceanAWSAccountWrapper awsWrapper = new OceanAWSAccountWrapper();
        awsWrapper.label = 'aws-hhs-cms-cciio-regtap';
        awsWrapper.value = 'aws-hhs-cms-cciio-regtap';
        awsWrapperList.add(awsWrapper);
                        
        OceanApplicationWrapper appWrapper = new OceanApplicationWrapper();
        appWrapper.id = app.id;
        appWrapper.name = 'OCEAN';
        appWrapper.acronym = 'OCEAN';
        appWrapper.adoName = 'BJones';
        appWrapper.awsAccounts = awsWrapperList;
        appWrapper.projectName = proj.name;
        appWrapper.projectNumber = proj.Project_Number__c;
        
        OceanController.getApplicationDetails(app.id);
        OceanController.getOceanRequestById(oceanRequest.id);
        OceanController.getApprovalHistory(oceanRequest.id);
        OceanController.getResourceRequestSummary(oceanRequest.Id);
        OceanController.getCostAndCount('OCEAN_Ec2Instance__c', oceanRequest.Id);
        OceanController.getCurrentOceanWave();
        OceanController.getAdminReviewStages();       
        OceanController.getWaveDetails();

        test.stopTest();
    }
}