SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Applications__c.object
<CustomObject>
    <label>Applications</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Ocean_Request__c.object
<CustomObject>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>COR/GTL Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to CRMT</fullName>
                </value>
                <value>
                    <fullName>Initial Review Complete</fullName>
                </value>
                <value>
                    <fullName>ROM Requested</fullName>
                </value>
                <value>
                    <fullName>ROM Received</fullName>
                </value>
                <value>
                    <fullName>ROM Reviewed</fullName>
                </value>
                <value>
                    <fullName>RFP Requested</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>RFP Reviewed</fullName>
                </value>
                <value>
                    <fullName>RFP Accepted</fullName>
                </value>
                <value>
                    <fullName>ADO Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>CRMT Intake Review</fullName>
                </value>
                <value>
                    <fullName>Attestation Requested</fullName>
                </value>
                <value>
                    <fullName>CRMT Intake Review Completed</fullName>
                </value>
                <value>
                    <fullName>ROM Approved</fullName>
                </value>
                <value>
                    <fullName>RFP Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ocean Request</label>
    <nameField>
        <label>Ocean_Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ocean_requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test Classes/Test_OceanApprovalProcess.cls
@isTest
public with sharing class Test_OceanApprovalProcess {
    public static testMethod void oceanApprovalProcessTest() {
        test.startTest();
        CollaborationGroup crmsGroup = new CollaborationGroup();
        crmsGroup.name = 'Cloud Resource Management Support Team';
        crmsGroup.CollaborationType = 'Public';
        insert crmsGroup;

        CollaborationGroup crmtGroup = new CollaborationGroup();
        crmtGroup.name = 'Cloud Resource Management Team';
        crmtGroup.CollaborationType = 'Public';
        insert crmtGroup;
        system.debug('crmtGroup:::'+crmtGroup.id);

        // CollaborationGroupMember grpMr = new CollaborationGroupMember();
        // grpMr.memberid = UserInfo.getUserId();
        // grpMr.CollaborationGroupId = crmsGroup.id;
        // insert grpMr;
        // CollaborationGroupMember grpMr1 = new CollaborationGroupMember();
        // grpMr1.memberid = UserInfo.getUserId();
        // grpMr1.CollaborationGroupId = crmtGroup.id;
        // insert grpMr1;

        Network myNetwork = [SELECT Id,name FROM Network WHERE Name = 'ocean-crm' LIMIT 1];
        system.debug('myNetwork:::'+myNetwork);

        // FeedItem feedToCG = new FeedItem();
        // feedToCG.Body ='The Cloud Resource Request is ready for Proposal Leadership Review.';
        // feedToCG.ParentId = crmtGroup.Id;
        // feedToCG.Type ='TextPost';
        // feedToCG.Visibility = 'AllUsers';
        // feedToCG.NetworkScope = myNetwork.id;
        // insert feedToCG;
        
        Applications__c app = TestDataFactory.getApplication();
        OCEAN_Request__c oceanRequest = TestDataFactory.getOceanRequest();
        // oceanRequest.Request_Status__c = 'COR/GTL Approval';
        // oceanRequest.CRMT_Request_Status__c = 'COR/GTL Approval';
        // oceanRequest.Review_Status__c = 'COR/GTL Approval';
        // update oceanRequest;
        // oceanRequest.Request_Status__c = 'CRMT Intake Review';
        // oceanRequest.CRMT_Request_Status__c = 'Initial Intake Review';
        // oceanRequest.Review_Status__c = 'CRMT Review';
        // update oceanRequest;
        OCEAN_Request__c oceanRequest1 = TestDataFactory.getNextOceanRequest();
        OCEAN_Request__c oceanRequest2 = TestDataFactory.getOceanRequestCORGTL();
        
        List<OCEAN_Request__c> oceanRequestList = new List<Ocean_Request__c>();
        oceanRequestList.add(oceanRequest);
        List<OCEAN_Request__c> oceanRequestList1 = new List<Ocean_Request__c>();
    //    oceanRequestList1.add(oceanRequest1);
        oceanRequestList1.add(oceanRequest2);
        
        OceanApprovalProcess controller = new OceanApprovalProcess();
        controller.submitForIntakeReview(oceanRequest);
        controller.approveIntakeReview(oceanRequest);
        controller.rejectIntakeReview(oceanRequest);
    //    controller.CRMTAdminReview(oceanRequestList,oceanRequestList1);
        test.stopTest();
    }
}