SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Applications__c.object
<CustomObject>
    <fields>
        <fullName>Application_Acronym__c</fullName>
        <label>Application Acronym</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/OCEAN_Ec2Instance__c.object
<CustomObject>
    <fields>
        <fullName>ADO_FUNDING_TYPE__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OnDemand</fullName>
                    <default>true</default>
                    <label>OnDemand</label>
                </value>
                <value>
                    <fullName>Standard, Reserved, 3yr, Partial Upfront</fullName>
                </value>
                <value>
                    <fullName>Standard, Reserved, 3yr, No Upfront</fullName>
                </value>
                <value>
                    <fullName>Standard, Reserved, 3yr, All Upfront</fullName>
                </value>
                <value>
                    <fullName>Standard, Reserved, 1yr, Partial Upfront</fullName>
                </value>
                <value>
                    <fullName>Standard, Reserved, 1yr, No Upfront</fullName>
                </value>
                <value>
                    <fullName>Standard, Reserved, 1yr, All Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 3yr, Partial Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 3yr, No Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 3yr, All Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 1yr, Partial Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 1yr, No Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 1yr, All Upfront</fullName>
                </value>
                <value>
                    <fullName>1 Yr All Upfront Convertible</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr All Upfront Convertible</label>
                </value>
                <value>
                    <fullName>1 Yr All Upfront Reserved</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr All Upfront Reserved</label>
                </value>
                <value>
                    <fullName>1 Yr No Upfront Convertible</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr No Upfront Convertible</label>
                </value>
                <value>
                    <fullName>1 Yr No Upfront Reserved</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr No Upfront Reserved</label>
                </value>
                <value>
                    <fullName>1 Yr Partial Upfront Convertible</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr Partial Upfront Convertible</label>
                </value>
                <value>
                    <fullName>1 Yr Partial Upfront Reserved</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr Partial Upfront Reserved</label>
                </value>
                <value>
                    <fullName>Convertible Reserved</fullName>
                    <isActive>false</isActive>
                    <label>Convertible Reserved</label>
                </value>
                <value>
                    <fullName>On-Demand</fullName>
                    <isActive>false</isActive>
                    <label>On-Demand</label>
                </value>
                <value>
                    <fullName>Standard Reserved</fullName>
                    <isActive>false</isActive>
                    <label>Standard Reserved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADO_Notes__c</fullName>
        <label>ADO Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AWS_Accounts__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AWS Accounts</label>
        <referenceTo>AWS_Accounts__c</referenceTo>
        <relationshipLabel>OCEAN_Ec2Instances</relationshipLabel>
        <relationshipName>OCEAN_Ec2Instances</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AWS_Availability_Zone__c</fullName>
        <label>AWS Availability Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EastVA_AZLookup</fullName>
                </value>
                <value>
                    <fullName>WestOR_AZlookup</fullName>
                </value>
                <value>
                    <fullName>us-east-1x</fullName>
                </value>
                <value>
                    <fullName>us-east-1y</fullName>
                </value>
                <value>
                    <fullName>us-east-1z</fullName>
                </value>
                <value>
                    <fullName>us-west-1x</fullName>
                </value>
                <value>
                    <fullName>us-west-1y</fullName>
                </value>
                <value>
                    <fullName>us-west-1z</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AWS_Region__c</fullName>
        <label>AWS Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>US East (N. Virginia)</fullName>
                    <default>true</default>
                    <label>US East (N. Virginia)</label>
                </value>
                <value>
                    <fullName>US West (Oregon)</fullName>
                </value>
                <value>
                    <fullName>US-East/US-Standard (Virginia)</fullName>
                    <isActive>false</isActive>
                    <label>US-East/US-Standard (Virginia)</label>
                </value>
                <value>
                    <fullName>US-West-2 (Oregon)</fullName>
                    <isActive>false</isActive>
                    <label>US-West-2 (Oregon)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Component__c</fullName>
        <label>Application Component</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Calculated_Cost__c</fullName>
        <label>Calculated Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Cost__c</fullName>
        <label>Estimated Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>OCEAN EC2 Instance</label>
    <nameField>
        <displayFormat>EC2-{0000}</displayFormat>
        <label>EC2 Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCEAN_Ec2Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Ocean_Request__c.object
<CustomObject>
    <fields>
        <fullName>AWSInstances__c</fullName>
        <label>AWS Resources</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VPC</fullName>
                </value>
                <value>
                    <fullName>EC2</fullName>
                </value>
                <value>
                    <fullName>EBS</fullName>
                </value>
                <value>
                    <fullName>ELB</fullName>
                </value>
                <value>
                    <fullName>RDS</fullName>
                </value>
                <value>
                    <fullName>RDS Backup Storage</fullName>
                </value>
                <value>
                    <fullName>EFS</fullName>
                </value>
                <value>
                    <fullName>S3</fullName>
                </value>
                <value>
                    <fullName>Data Transfer</fullName>
                </value>
                <value>
                    <fullName>Redshift</fullName>
                </value>
                <value>
                    <fullName>EMR</fullName>
                </value>
                <value>
                    <fullName>DynamoDB</fullName>
                </value>
                <value>
                    <fullName>Workspaces</fullName>
                </value>
                <value>
                    <fullName>Quicksight</fullName>
                </value>
                <value>
                    <fullName>Lambda</fullName>
                </value>
                <value>
                    <fullName>Other Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ApplicationName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Name</label>
        <referenceTo>Applications__c</referenceTo>
        <relationshipName>ocean_requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Acronym__c</fullName>
        <label>Application Acronym</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assumptions__c</fullName>
        <inlineHelpText>Document any assumptions related to your application and this cloud resource request you would like to share with the Cloud Resource Management Team.</inlineHelpText>
        <label>Assumptions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Current_Approved_Resources__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Approved Resources</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MonthsInPoP__c</fullName>
        <label>Months In Period Of Performance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Additional_Funding_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Additional Funding Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PeriodOfPerformance__c</fullName>
        <label>Period Of Performance</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <label>Project_Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>COR/GTL Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to CRMT</fullName>
                </value>
                <value>
                    <fullName>Initial Review Complete</fullName>
                </value>
                <value>
                    <fullName>ROM Requested</fullName>
                </value>
                <value>
                    <fullName>ROM Received</fullName>
                </value>
                <value>
                    <fullName>ROM Reviewed</fullName>
                </value>
                <value>
                    <fullName>RFP Requested</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>RFP Reviewed</fullName>
                </value>
                <value>
                    <fullName>RFP Accepted</fullName>
                </value>
                <value>
                    <fullName>ADO Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>CRMT Intake Review</fullName>
                </value>
                <value>
                    <fullName>Attestation Requested</fullName>
                </value>
                <value>
                    <fullName>CRMT Intake Review Completed</fullName>
                </value>
                <value>
                    <fullName>ROM Approved</fullName>
                </value>
                <value>
                    <fullName>RFP Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Estimated_Amount__c</fullName>
        <label>Total Estimated Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Estimated_Cost__c</fullName>
        <label>Total Estimated Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Ocean Request</label>
    <nameField>
        <label>Ocean_Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ocean_requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OceanReport.cls
public with sharing class OceanReport {
    @AuraEnabled
    public static List<Ocean_Request__c> getOceanRequestsForExport(){
        return [SELECT Id, Name, Approval_Comments__c, Review_Outcome__c, CreatedDate, AWSInstances__c, Review_Status__c, CRMT_Request_Status__c,ApplicationName__r.Application_Acronym__c,Assumptions__c,  Current_Approved_Resources__c, MonthsInPoP__c, No_Additional_Funding_Requested__c,Total_Estimated_Cost__c, PeriodOfPerformance__c, ProjectName__c, Request_Status__c, Submitted_Date__c, Total_Estimated_Amount__c,
                RFP_Received_Date__c, ROM_Received_Date__c, RFP_Requested_Date__c, ROM_Requested_Date__c 
                FROM OCEAN_Request__c];
    }

    @AuraEnabled
    public static List<OCEAN_Ec2Instance__c> getEc2InstancesForExport(){
        return [SELECT Id,Name,ADO_FUNDING_TYPE__c,ADO_Notes__c,Application_Component__c,AWS_Availability_Zone__c, AWS_Accounts__c,AWS_Region__c,Calculated_Cost__c,Cloud_Resource_Projection__c,Tenancy__c,EC2_Instance_Type__c,Estimated_Cost__c,Instance_Quantity__c,PerInstanceUptimePerDay__c,PerInstanceUptimePerMonth__c,Per_Instance_Running_Months_in_Remaining__c,Platform__c,Resource_Status__c,Environment__c FROM OCEAN_Ec2Instance__c ORDER BY  CreatedDate];      
    }
}