SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/AWS_PRICING_EC2__c.object
<CustomObject>
    <fields>
        <fullName>CapacityStatus__c</fullName>
        <label>CapacityStatus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InstanceType__c</fullName>
        <label>InstanceType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeaseContractLength__c</fullName>
        <label>LeaseContractLength</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfferingClass__c</fullName>
        <label>OfferingClass</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OperatingSystem__c</fullName>
        <label>OperatingSystem</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreInstalledSW__c</fullName>
        <label>PreInstalledSW</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PricePerUnit__c</fullName>
        <label>PricePerUnit</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PurchaseOption__c</fullName>
        <label>PurchaseOption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tenancy__c</fullName>
        <label>Tenancy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TermType__c</fullName>
        <label>TermType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AWS_PRICING_EC2</label>
    <nameField>
        <label>AWS_PRICING_EC2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AWS_PRICING_EC2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Ec2PricingBatch.cls
global class Ec2PricingBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
       String query = 'SELECT PricePerUnit__c, Unit__c FROM AWS_PRICING_EC2__C WHERE OperatingSystem__c	= :pricingRequest.platform AND PreInstalledSW__c = :pricingRequest.preInstalledSW AND InstanceType__c= :pricingRequest.instanceType'
       +' '+'AND Location__c = :pricingRequest.region AND Tenancy__c= :pricingRequest.tenancy AND TermType__c = :pricingRequest.termType AND OfferingClass__c = :pricingRequest.offeringClass AND LeaseContractLength__c =:pricingRequest.leaseContractLength' 
       +' '+'AND PurchaseOption__c =:pricingRequest.purchaseOption AND CapacityStatus__c = :pricingRequest.capacityStatus';
       return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<AWS_PRICING_EC2__C> scope){
        for(AWS_PRICING_EC2__C awsEc2 : scope) {
          //  insert awsEc2;
        }
    }    
    global void finish(Database.BatchableContext bc){
        
    }    
}