SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/OCEAN_Ec2Instance__c.object
<CustomObject>
    <fields>
        <fullName>EC2_Instance_Type__c</fullName>
        <inlineHelpText>The type of instances you expect to launch with this configuration.</inlineHelpText>
        <label>EC2 Instance Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>t1.micro</fullName>
                </value>
                <value>
                    <fullName>t2.nano</fullName>
                </value>
                <value>
                    <fullName>t2.micro</fullName>
                </value>
                <value>
                    <fullName>t2.small</fullName>
                </value>
                <value>
                    <fullName>t2.medium</fullName>
                </value>
                <value>
                    <fullName>t2.large</fullName>
                </value>
                <value>
                    <fullName>t2.xlarge</fullName>
                </value>
                <value>
                    <fullName>t2.2xlarge</fullName>
                </value>
                <value>
                    <fullName>m4.large</fullName>
                </value>
                <value>
                    <fullName>m4.xlarge</fullName>
                </value>
                <value>
                    <fullName>m4.2xlarge</fullName>
                </value>
                <value>
                    <fullName>m4.4xlarge</fullName>
                </value>
                <value>
                    <fullName>m4.10xlarge</fullName>
                </value>
                <value>
                    <fullName>m4.16xlarge</fullName>
                </value>
                <value>
                    <fullName>m5.large</fullName>
                </value>
                <value>
                    <fullName>m5.xlarge</fullName>
                </value>
                <value>
                    <fullName>m5.2xlarge</fullName>
                </value>
                <value>
                    <fullName>m5.4xlarge</fullName>
                </value>
                <value>
                    <fullName>m5.12xlarge</fullName>
                </value>
                <value>
                    <fullName>m5.24xlarge</fullName>
                </value>
                <value>
                    <fullName>m3.medium</fullName>
                </value>
                <value>
                    <fullName>m3.large</fullName>
                </value>
                <value>
                    <fullName>m3.xlarge</fullName>
                </value>
                <value>
                    <fullName>m3.2xlarge</fullName>
                </value>
                <value>
                    <fullName>c5.large</fullName>
                </value>
                <value>
                    <fullName>c5.xlarge</fullName>
                </value>
                <value>
                    <fullName>c5.2xlarge</fullName>
                </value>
                <value>
                    <fullName>c5.4xlarge</fullName>
                </value>
                <value>
                    <fullName>c5.9xlarge</fullName>
                </value>
                <value>
                    <fullName>c5.18xlarge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OCEAN EC2 Instance</label>
    <nameField>
        <displayFormat>EC2-{0000}</displayFormat>
        <label>EC2 Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCEAN_Ec2Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OceanDataOptions.cls
public with sharing class OceanDataOptions {     
    @AuraEnabled(cacheable=true)
    public static Map < String, String > getAwsEc2Types() {   
         Map < String, String > d = new Map < String, String >();     
         Schema.DescribeFieldResult fieldResult = OCEAN_Ec2Instance__c.EC2_Instance_Type__c	.getDescribe();         
         List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();         
         for( Schema.PicklistEntry pickListVal : ple) {             
             d.put(pickListVal.getLabel(), pickListVal.getLabel());        
         }  
         return d;
   } 
 }