SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/OCEAN_Ec2Instance__c.object
<CustomObject>
    <label>OCEAN EC2 Instance</label>
    <nameField>
        <displayFormat>EC2-{0000}</displayFormat>
        <label>EC2 Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCEAN_Ec2Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Ocean_Request__c.object
<CustomObject>
    <fields>
        <fullName>AWSInstances__c</fullName>
        <label>AWS Resources</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VPC</fullName>
                </value>
                <value>
                    <fullName>EC2</fullName>
                </value>
                <value>
                    <fullName>EBS</fullName>
                </value>
                <value>
                    <fullName>ELB</fullName>
                </value>
                <value>
                    <fullName>RDS</fullName>
                </value>
                <value>
                    <fullName>RDS Backup Storage</fullName>
                </value>
                <value>
                    <fullName>EFS</fullName>
                </value>
                <value>
                    <fullName>S3</fullName>
                </value>
                <value>
                    <fullName>Data Transfer</fullName>
                </value>
                <value>
                    <fullName>Redshift</fullName>
                </value>
                <value>
                    <fullName>EMR</fullName>
                </value>
                <value>
                    <fullName>DynamoDB</fullName>
                </value>
                <value>
                    <fullName>Workspaces</fullName>
                </value>
                <value>
                    <fullName>Quicksight</fullName>
                </value>
                <value>
                    <fullName>Lambda</fullName>
                </value>
                <value>
                    <fullName>Other Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cloud_Service_Provider_Project_Number__c</fullName>
        <label>Cloud Service Provider Project Number</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <label>Project_Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Ocean Request</label>
    <nameField>
        <label>Ocean_Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ocean_requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test Classes/Test_OceanController.cls
@isTest
public with sharing class Test_OceanController {
    public static testMethod void oceanControllerTest(){
        test.startTest();
        OCEAN_Request__c oceanRequest = new OCEAN_Request__c();
        oceanRequest.Cloud_Service_Provider_Project_Number__c = '48';
        oceanRequest.AWSInstances__c = 'EC2';
        oceanRequest.ProjectName__c = 'Ocean';
        insert oceanRequest;

        OceanController.getOceanRequestById(oceanRequest.id);
        OceanController.getApprovalHistory(oceanRequest.id);
        OceanController.getResourceRequestSummary(oceanRequest.Id);
        OceanController.getCostAndCount('OCEAN_Ec2Instance__c', oceanRequest.Id);
        OceanController.getCurrentOceanWave();
        OceanController.getAdminReviewStages();
        OceanController.getWaveDetails();

        test.stopTest();
    }
}