SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Ocean_Request__c.object
<CustomObject>
    <fields>
        <fullName>AWSInstances__c</fullName>
        <label>AWS Resources</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VPC</fullName>
                </value>
                <value>
                    <fullName>EC2</fullName>
                </value>
                <value>
                    <fullName>EBS</fullName>
                </value>
                <value>
                    <fullName>ELB</fullName>
                </value>
                <value>
                    <fullName>RDS</fullName>
                </value>
                <value>
                    <fullName>RDS Backup Storage</fullName>
                </value>
                <value>
                    <fullName>EFS</fullName>
                </value>
                <value>
                    <fullName>S3</fullName>
                </value>
                <value>
                    <fullName>Data Transfer</fullName>
                </value>
                <value>
                    <fullName>Redshift</fullName>
                </value>
                <value>
                    <fullName>EMR</fullName>
                </value>
                <value>
                    <fullName>DynamoDB</fullName>
                </value>
                <value>
                    <fullName>Workspaces</fullName>
                </value>
                <value>
                    <fullName>Quicksight</fullName>
                </value>
                <value>
                    <fullName>Lambda</fullName>
                </value>
                <value>
                    <fullName>Other Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Acronym__c</fullName>
        <label>Application Acronym</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Name__c</fullName>
        <label>Application Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assumptions__c</fullName>
        <inlineHelpText>Document any assumptions related to your application and this cloud resource request you would like to share with the Cloud Resource Management Team.</inlineHelpText>
        <label>Assumptions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Cloud_Service_Provider_Project_Number__c</fullName>
        <label>Cloud Service Provider Project Number</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Approved_Resources__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Approved Resources</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MonthsInPoP__c</fullName>
        <label>Months In Period Of Performance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Additional_Funding_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Additional Funding Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_AWS_Accounts__c</fullName>
        <label>Number of AWS Accounts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Option_Year_End_Date__c</fullName>
        <label>Option Year End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Option_Year_Start_Date__c</fullName>
        <label>Option Year Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Option_Year__c</fullName>
        <label>Option Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PeriodOfPerformance__c</fullName>
        <label>Period Of Performance</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectName__c</fullName>
        <label>Project_Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>COR/GTL Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted to CRMT</fullName>
                </value>
                <value>
                    <fullName>Initial Review Complete</fullName>
                </value>
                <value>
                    <fullName>ROM Requested</fullName>
                </value>
                <value>
                    <fullName>ROM Received</fullName>
                </value>
                <value>
                    <fullName>ROM Reviewed</fullName>
                </value>
                <value>
                    <fullName>RFP Requested</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>RFP Reviewed</fullName>
                </value>
                <value>
                    <fullName>RFP Accepted</fullName>
                </value>
                <value>
                    <fullName>ADO Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>CRMT Intake Review</fullName>
                </value>
                <value>
                    <fullName>Attestation Requested</fullName>
                </value>
                <value>
                    <fullName>CRMT Intake Review Completed</fullName>
                </value>
                <value>
                    <fullName>ROM Approved</fullName>
                </value>
                <value>
                    <fullName>RFP Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Estimated_Amount__c</fullName>
        <label>Total Estimated Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wave_Submitted__c</fullName>
        <label>Wave Submitted</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Ocean Request</label>
    <nameField>
        <label>Ocean_Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ocean_requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/objects/Ocean_Request__c.object
    <fields>
        <fullName>ADOName__c</fullName>
        <label>ADOName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>

SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/objects/Ocean_Request__c.object
    <fields>
        <fullName>AWSAccountName__c</fullName>
        <label>AWSAccountName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>

SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/Option_Year__c.object
<CustomObject>
    <fields>
        <fullName>Option_Year_End_Date__c</fullName>
        <label>Option Year End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Option_Year_Start_Date__c</fullName>
        <label>Option Year Start Date</label>
        <type>Date</type>
    </fields>
    <label>Option Year</label>
    <nameField>
        <label>CSP Option Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Option Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OceanAllRequests.cls
public with sharing class OceanAllRequests {
    @AuraEnabled(cacheable=true)
    public static List<OCEAN_Request__c> getDraftRequests(String status){
        return[SELECT CreatedDate, ADOName__c, AWSInstances__c, Application_Acronym__c,Application_Name__c, Assumptions__c, AWSAccountName__c, Cloud_Service_Provider_Project_Number__c, Current_Approved_Resources__c, MonthsInPoP__c, No_Additional_Funding_Requested__c, Number_of_AWS_Accounts__c, Option_Year__c, Option_Year_End_Date__c, Option_Year_Start_Date__c, PeriodOfPerformance__c, ProjectName__c, Request_Status__c, Submitted_Date__c, Total_Estimated_Amount__c, Wave_Submitted__c FROM OCEAN_Request__c WHERE Request_Status__c = :status ORDER BY Submitted_Date__c];
    }
    @AuraEnabled(cacheable=true)
    public static SObject getOceanRequestById(String id){
    SObject o =  [SELECT CreatedDate, ADOName__c, AWSInstances__c, Application_Acronym__c,Application_Name__c, Assumptions__c, AWSAccountName__c, Cloud_Service_Provider_Project_Number__c, Current_Approved_Resources__c, MonthsInPoP__c, No_Additional_Funding_Requested__c, Number_of_AWS_Accounts__c, Option_Year__c, Option_Year_End_Date__c, Option_Year_Start_Date__c, PeriodOfPerformance__c, ProjectName__c, Request_Status__c, Submitted_Date__c, Total_Estimated_Amount__c, Wave_Submitted__c FROM OCEAN_Request__c WHERE Id = :id ];
    return o;
    }
}