SF-Custom-Objects/salesforce_ant_46.0/sample/retrieveUnpackaged/objects/OCEAN_Ec2Instance__c.object
<CustomObject>
    <fields>
        <fullName>ADO_FUNDING_TYPE__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OnDemand</fullName>
                    <default>true</default>
                    <label>OnDemand</label>
                </value>
                <value>
                    <fullName>Standard, Reserved, 3yr, Partial Upfront</fullName>
                </value>
                <value>
                    <fullName>Standard, Reserved, 3yr, No Upfront</fullName>
                </value>
                <value>
                    <fullName>Standard, Reserved, 3yr, All Upfront</fullName>
                </value>
                <value>
                    <fullName>Standard, Reserved, 1yr, Partial Upfront</fullName>
                </value>
                <value>
                    <fullName>Standard, Reserved, 1yr, No Upfront</fullName>
                </value>
                <value>
                    <fullName>Standard, Reserved, 1yr, All Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 3yr, Partial Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 3yr, No Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 3yr, All Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 1yr, Partial Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 1yr, No Upfront</fullName>
                </value>
                <value>
                    <fullName>Convertible, Reserved, 1yr, All Upfront</fullName>
                </value>
                <value>
                    <fullName>1 Yr All Upfront Convertible</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr All Upfront Convertible</label>
                </value>
                <value>
                    <fullName>1 Yr All Upfront Reserved</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr All Upfront Reserved</label>
                </value>
                <value>
                    <fullName>1 Yr No Upfront Convertible</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr No Upfront Convertible</label>
                </value>
                <value>
                    <fullName>1 Yr No Upfront Reserved</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr No Upfront Reserved</label>
                </value>
                <value>
                    <fullName>1 Yr Partial Upfront Convertible</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr Partial Upfront Convertible</label>
                </value>
                <value>
                    <fullName>1 Yr Partial Upfront Reserved</fullName>
                    <isActive>false</isActive>
                    <label>1 Yr Partial Upfront Reserved</label>
                </value>
                <value>
                    <fullName>Convertible Reserved</fullName>
                    <isActive>false</isActive>
                    <label>Convertible Reserved</label>
                </value>
                <value>
                    <fullName>On-Demand</fullName>
                    <isActive>false</isActive>
                    <label>On-Demand</label>
                </value>
                <value>
                    <fullName>Standard Reserved</fullName>
                    <isActive>false</isActive>
                    <label>Standard Reserved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADO_Notes__c</fullName>
        <label>ADO Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AWS_Availability_Zone__c</fullName>
        <label>AWS Availability Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EastVA_AZLookup</fullName>
                </value>
                <value>
                    <fullName>WestOR_AZlookup</fullName>
                </value>
                <value>
                    <fullName>us-east-1x</fullName>
                </value>
                <value>
                    <fullName>us-east-1y</fullName>
                </value>
                <value>
                    <fullName>us-east-1z</fullName>
                </value>
                <value>
                    <fullName>us-west-1x</fullName>
                </value>
                <value>
                    <fullName>us-west-1y</fullName>
                </value>
                <value>
                    <fullName>us-west-1z</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AWS_Region__c</fullName>
        <label>AWS Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>US East (N. Virginia)</fullName>
                    <default>true</default>
                    <label>US East (N. Virginia)</label>
                </value>
                <value>
                    <fullName>US West (Oregon)</fullName>
                </value>
                <value>
                    <fullName>US-East/US-Standard (Virginia)</fullName>
                    <isActive>false</isActive>
                    <label>US-East/US-Standard (Virginia)</label>
                </value>
                <value>
                    <fullName>US-West-2 (Oregon)</fullName>
                    <isActive>false</isActive>
                    <label>US-West-2 (Oregon)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Component__c</fullName>
        <label>Application Component</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cloud_Resource_Projection__c</fullName>
        <label>Cloud Resource Projection</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC2_Instance_Type__c</fullName>
        <inlineHelpText>The type of instances you expect to launch with this configuration.</inlineHelpText>
        <label>EC2 Instance Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>t1.micro</fullName>
                </value>
                <value>
                    <fullName>t2.nano</fullName>
                </value>
                <value>
                    <fullName>t2.micro</fullName>
                </value>
                <value>
                    <fullName>t2.small</fullName>
                </value>
                <value>
                    <fullName>t2.medium</fullName>
                </value>
                <value>
                    <fullName>t2.large</fullName>
                </value>
                <value>
                    <fullName>t2.xlarge</fullName>
                </value>
                <value>
                    <fullName>t2.2xlarge</fullName>
                </value>
                <value>
                    <fullName>m4.large</fullName>
                </value>
                <value>
                    <fullName>m4.xlarge</fullName>
                </value>
                <value>
                    <fullName>m4.2xlarge</fullName>
                </value>
                <value>
                    <fullName>m4.4xlarge</fullName>
                </value>
                <value>
                    <fullName>m4.10xlarge</fullName>
                </value>
                <value>
                    <fullName>m4.16xlarge</fullName>
                </value>
                <value>
                    <fullName>m5.large</fullName>
                </value>
                <value>
                    <fullName>m5.xlarge</fullName>
                </value>
                <value>
                    <fullName>m5.2xlarge</fullName>
                </value>
                <value>
                    <fullName>m5.4xlarge</fullName>
                </value>
                <value>
                    <fullName>m5.12xlarge</fullName>
                </value>
                <value>
                    <fullName>m5.24xlarge</fullName>
                </value>
                <value>
                    <fullName>m3.medium</fullName>
                </value>
                <value>
                    <fullName>m3.large</fullName>
                </value>
                <value>
                    <fullName>m3.xlarge</fullName>
                </value>
                <value>
                    <fullName>m3.2xlarge</fullName>
                </value>
                <value>
                    <fullName>c5.large</fullName>
                </value>
                <value>
                    <fullName>c5.xlarge</fullName>
                </value>
                <value>
                    <fullName>c5.2xlarge</fullName>
                </value>
                <value>
                    <fullName>c5.4xlarge</fullName>
                </value>
                <value>
                    <fullName>c5.9xlarge</fullName>
                </value>
                <value>
                    <fullName>c5.18xlarge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Cost__c</fullName>
        <label>Estimated Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Instance_Quantity__c</fullName>
        <inlineHelpText>The number of instances you expect to launch with this configuration.</inlineHelpText>
        <label>Instance Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PerInstanceUptimePerDay__c</fullName>
        <inlineHelpText>The number of hours you expect the instances to run in a day.</inlineHelpText>
        <label>Per Instance Running Hours/Day</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PerInstanceUptimePerMonth__c</fullName>
        <inlineHelpText>The number of days you expect the instances to run in a month.</inlineHelpText>
        <label>Per Instance Running Days/Month</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Linux, SQL Std</fullName>
                </value>
                <value>
                    <fullName>Linux, SQL Ent</fullName>
                </value>
                <value>
                    <fullName>Linux, SQL Web</fullName>
                </value>
                <value>
                    <fullName>RHEL</fullName>
                </value>
                <value>
                    <fullName>SUSE</fullName>
                </value>
                <value>
                    <fullName>Windows, SQL Ent</fullName>
                </value>
                <value>
                    <fullName>Windows, SQL Std</fullName>
                </value>
                <value>
                    <fullName>Windows, SQL Web</fullName>
                </value>
                <value>
                    <fullName>Linux</fullName>
                    <isActive>false</isActive>
                    <label>Linux</label>
                </value>
                <value>
                    <fullName>Windows</fullName>
                    <isActive>false</isActive>
                    <label>Windows</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resource_Status__c</fullName>
        <label>Resource Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Discontinuation</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Unapproved</fullName>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                    <isActive>false</isActive>
                    <label>Continuation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OCEAN EC2 Instance</label>
    <nameField>
        <displayFormat>EC2-{0000}</displayFormat>
        <label>EC2 Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCEAN_Ec2Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/objects/OCEAN_Ec2Instance__c.object
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <length>100</length>
        <type>Text</type>
    </fields>

SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/objects/OCEAN_Ec2Instance__c.object
    <fields>
        <fullName>InstanceID__c</fullName>
        <displayFormat>EC2-{00000}</displayFormat>
        <label>InstanceID</label>
        <type>AutoNumber</type>
    </fields>

SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/objects/OCEAN_Ec2Instance__c.object
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>

SF-Custom-Objects/salesforce_ant_46.0/sample/codepkg/objects/OCEAN_Ec2Instance__c.object
    <fields>
        <fullName>Wave_Submitted__c</fullName>
        <label>Wave Submitted</label>
        <length>100</length>
        <type>Text</type>
    </fields>

force-app/main/default/classes/OceanEc2ComputeController.cls
public with sharing class OceanEc2ComputeController {
    @AuraEnabled(Cacheable = true)
    public static List<OCEAN_Ec2Instance__c> getEc2Instances(String oceanRequestId){
        return [SELECT ADO_FUNDING_TYPE__c, ADO_Notes__c,Application__c, Application_Component__c, AWS_Availability_Zone__c, AWS_Region__c, Cloud_Resource_Projection__c, EC2_Instance_Type__c, Estimated_Cost__c, Instance_Quantity__c, InstanceID__c, PerInstanceUptimePerDay__c, PerInstanceUptimePerMonth__c, Platform__c, Project_Name__c, Resource_Status__c, Tier__c, TotalUptimePerMonth__c, TotalUptimePerYear__c, Wave_Submitted__c FROM OCEAN_Ec2Instance__c WHERE Ocean_Request_Id__c =:oceanRequestId ORDER BY Tier__c limit 10];
    }

    @AuraEnabled
    public static void deleteEc2Instances(list<Id> lstIds){
        try {
            list<OCEAN_Ec2Instance__c> lstToRemove = new list<OCEAN_Ec2Instance__c>();
            System.debug('lstIds ====> '+lstIds);
            for(Id idIns : lstIds) {
                lstToRemove.add(new OCEAN_Ec2Instance__c(Id = idIns));
            }
            if(!lstToRemove.isEmpty()) {
                delete lstToRemove;
            }
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

}